### ISSUE TITLE
Day 2

### ISSUE THREAD

**Issue by Erin-Codes** [Moipatit/Day-2#1]
# Thank you for taking the time to work through setting up a simple server and taking some additional measures to harden its security. 

### For Task 1 you have made a good attempt and you're definitely on the right track, however, there are just a few minor issues in your script that I'd like kindly to point out:

- (More of a syntax issue) In lines 3 and 4 of your script the opening quotes for the input strings are not being closed before the variable names 'original' and 'rename'. An alternative method could be to 'echo' the prompt instruction and 'read' the input separately(I'd still recommend your initial approach with the `-p` flag). 

**For example:** 
`echo "Enter filename"`
`read original`
`echo "Enter new name"`
`read new_name`

- A few issues with your if block is that the `if` keyword is attached to the opening square bracket(see the `-f` is attached to the square bracket as well) and that you have not indicated the 'end of the if statement block with `fi`. Without the `fi` keyword at the end of an if statement, bash would not know when the if statement ends or whether it has ended. This can occasionally produce a syntax error.
**For example:**
`if [ ! -f "$original"]; then`
`     echo "This file does not exist"`
`     exit 1`
`fi`

- The $ and ( ) can be removed from the `mv` command as these are not required for execution.

## Please Note that these are all simply syntax issues (very likely to occur when learning a new language/syntax). Your logic here is spot on, which is what counts. :)

**Comment by Moipatit** [comment]
Thank you for your feedback.
